"""
Django settings for canteen_web project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from configparser import ConfigParser

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

cfg = ConfigParser(interpolation=None)
if not cfg.read(os.path.join(BASE_DIR, 'config.ini')):
    raise FileNotFoundError('config.ini does not exist. Please create it as described in the README')

SECRET_KEY = cfg['secrets']['secret_key']

if 'production' in cfg:
    ALLOWED_HOSTS = cfg['production']['hosts'].split()
else:
    ALLOWED_HOSTS = []

# Disable debug mode if the hosts setting exists and is nonempty
DEBUG = not bool(ALLOWED_HOSTS)

# Where to collect static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Configure SMTP if [mail] section exists in config.ini
if 'mail' in cfg:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    sec = cfg['mail']
    EMAIL_HOST = sec['host']
    EMAIL_PORT = sec.get('port', None)
    # SSL connection (implicit)
    EMAIL_USE_SSL = sec.get('use_ssl', None)
    # STARTTLS (explicit)
    EMAIL_USE_TLS = sec.get('use_tls', None)
    EMAIL_HOST_USER = sec['user']
    EMAIL_HOST_PASSWORD = sec['password']
else:
    # If not configured (development), print emails to the console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
#
# GeoDjango db backend modules are named for the spatial db plugins for
# nonspatial dbs, so map postgresql and sqlite3 to the names of their
# respective plugins.
engine = {'postgresql':'postgis','sqlite3':'spatialite'}.get(cfg['db']['engine'], cfg['db']['engine'])

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.' + engine,
        'NAME': cfg['db'].get('name', None),
        'USER': cfg['db'].get('user', None),
        'PASSWORD': cfg['db'].get('password', None),
        'HOST': cfg['db'].get('host', None),
        'PORT': cfg['db'].get('port', None),
    }
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'canteen',
    'canteen_api',
    'canteen_browser',
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.DjangoModelPermissions',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'canteen_web.middleware.MethodOverrideMiddleware',
]

ROOT_URLCONF = 'canteen_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'canteen_web.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
