# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purityreport',
            options={'permissions': (('view_purityreport', 'Can view purity report'),)},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('view_report', 'Can view report'),)},
        ),
        migrations.AlterField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
