# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_view_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Waste'), (1, 'Treatable-Clear'), (2, 'Treatable-Muddy'), (3, 'Potable')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bottled'), (1, 'Well'), (2, 'Stream'), (3, 'Lake'), (4, 'Spring'), (5, 'Other')]),
        ),
    ]
