# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_report_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purityreport',
            name='contaminant_ppm',
        ),
        migrations.RemoveField(
            model_name='purityreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='purityreport',
            name='virus_ppm',
        ),
        migrations.AddField(
            model_name='purityreport',
            name='contaminantPPM',
            field=models.FloatField(default=0, verbose_name='contaminant PPM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purityreport',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='purityreport',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purityreport',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purityreport',
            name='virusPPM',
            field=models.FloatField(default=0, verbose_name='virus PPM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purityreport',
            name='condition',
            field=models.IntegerField(choices=[(0, 'Safe'), (1, 'Treatable'), (2, 'Unsafe')]),
        ),
        migrations.AlterField(
            model_name='purityreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purity_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
