# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 01:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purityreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='purityreport',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.AddField(
            model_name='purityreport',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326, verbose_name='location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326, verbose_name='location'),
            preserve_default=False,
        ),
    ]
